In [1]:
import pandas as pd
import tensorflow as tf

#과거의 데이터를 준비


In [13]:
directory = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(directory)
print(iris.shape)
iris = pd.get_dummies(iris)
print(iris.shape)

(150, 5)
(150, 7)


In [14]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [15]:
independent =  iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
independent_train = independent[:-5]
independent_test = independent[-5:]
print("independent_train : ", independent_train.shape)
print("independent_test : ", independent_test.shape)

dependent =  iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
dependent_train = dependent[:-5]
dependent_test = dependent[-5:]
print("dependent_train : ", dependent_train.shape)
print("dependent_test : ", dependent_test.shape)

independent_train :  (145, 4)
independent_test :  (5, 4)
dependent_train :  (145, 3)
dependent_test :  (5, 3)


#모델설계

In [27]:
X = tf.keras.layers.Input(shape = [4])
H = tf.keras.layers.Dense(8, activation = "swish")(X)
H = tf.keras.layers.Dense(32, activation = "swish")(H)
H = tf.keras.layers.Dense(64, activation = "swish")(H)
Y = tf.keras.layers.Dense(3, activation = "softmax")(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics="accuracy")

In [28]:
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_16 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_17 (Dense)             (None, 32)                288       
_________________________________________________________________
dense_18 (Dense)             (None, 64)                2112      
_________________________________________________________________
dense_19 (Dense)             (None, 3)                 195       
Total params: 2,635
Trainable params: 2,635
Non-trainable params: 0
_________________________________________________________________


#모델 학습시키기

In [29]:
model.fit(independent_train, dependent_train, epochs=90, verbose = 0)
model.fit(independent_train, dependent_train, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1130 - accuracy: 0.9517
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1021 - accuracy: 0.9586
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0945 - accuracy: 0.9655
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0966 - accuracy: 0.9517
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0933 - accuracy: 0.9655
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1032 - accuracy: 0.9724
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0962 - accuracy: 0.9586
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0928 - accuracy: 0.9724
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1149 - accuracy: 0.9379
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0939 - accuracy: 0.9586


#모델 이용하기

In [30]:
print(model.predict(independent_test))

[[1.6353630e-08 4.8627505e-01 5.1372492e-01]
 [3.6703000e-08 5.9455526e-01 4.0544468e-01]
 [9.4599706e-09 3.3764222e-01 6.6235775e-01]
 [3.1287387e-10 4.1085754e-02 9.5891428e-01]
 [5.9520175e-09 1.7326565e-01 8.2673436e-01]]


In [33]:
print(dependent_test)

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
